### ISSUE TITLE
IPv6 Only

### ISSUE THREAD

**Issue by hianghokung** [alphabt/asuswrt-merlin-ddns-cloudflare#10]
Hello, I have a need, but I don't know how to modify the script. My network environment has an IPv6 public network address, but no IPv4 public network address, I want DDNS to update only IPv6. Want the script to give the user an option to UPDATE_IPv4.

**Comment by alphabt** [comment]
Hi @hianghokung. This script doesn't support only IPv6 and I suggest you look into using [In-a-Dyn](https://github.com/RMerl/asuswrt-merlin.ng/wiki/DDNS-services) that's now built-in for Asuswrt-Merlin to update your DDNS. This is what I currently use for my domains on Cloudflare, and I think In-a-Dyn supports IPv6 as well.

Since I longer user this script myself, you're welcome to submit a PR to add support for IPv6 only mode.

**Comment by hianghokung** [comment]
> Hi @hianghokung. This script doesn't support only IPv6 and I suggest you look into using [In-a-Dyn](https://github.com/RMerl/asuswrt-merlin.ng/wiki/DDNS-services) that's now built-in for Asuswrt-Merlin to update your DDNS. This is what I currently use for my domains on Cloudflare, and I think In-a-Dyn supports IPv6 as well.
> 
> Since I longer user this script myself, you're welcome to submit a PR to add support for IPv6 only mode.

Oh, thank you for your advice！
