### ISSUE TITLE
Stuck on "Applying Settings"

### ISSUE THREAD

**Issue by epicylon** [alphabt/asuswrt-merlin-ddns-cloudflare#3]
(OSX) (RT-AC66U_380.70_0.trx)

I could not successfully SSH into the router so I telnet'd and 
`touch /jffs/scripts/ddns-script`
and
`nano /jffs/scripts/ddns-script`

after this I filled out variables accordingly. 

I got to the "Applying Settings" screen as I hit "Save" - left it over night, but still on the same screen.

**Comment by alphabt** [comment]
You might've named the script incorrectly. It should be `ddns-start` instead of `ddns-script`.

I would check the log to see if there's anything actionable. Under `Advanced Settings` go to `System Log` and look for any line tagged with [ddns-start] and see if there's any error.

Additionally you can also try running the command directly in ssh to see if it returns any error. Remember to pass in an IP as the sole argument to the script. For example:

```/jffs/scripts/ddns-start <IP>```
